
clc
clear all
close all
feature('GetCPU')
% 
% 
% % -------------------------> SPECIFY HERE PATH IN WHICH REPLICATION PACKAGE IS STORED:
% superpath = 'P:\ECB business areas\DGI\IPA\Personal folders\Georgiadis\Research\US MP normalization\GJ 2025 JIE replication';

bvarpath = cd;
cd ..
superpath = cd;
eval(['cd ''',bvarpath,''''])

generalpath_bvars = strcat(superpath,'\BVARs');
datapath_bvars = strcat(generalpath_bvars,'\Data BVARs');
figurepath_bvars = strcat(generalpath_bvars,'\Figures BVARs');
restoredefaultpath
addpath(strcat(generalpath_bvars,'\Matlab subroutines'))
eval(['cd ''',generalpath_bvars,' '' '])
mkdir(generalpath_bvars,'Figures BVARs')
warning('off','all')


%% Start parallel pool
delete(gcp('nocreate'))
numcores = feature('numcores');
numcores_logical = getenv('NUMBER_OF_PROCESSORS');
core_info = evalc('feature(''numcores'')');
local = parcluster('local');
local.NumWorkers = 24;
saveProfile(local)
pool = local.parpool(24);

%% Load data
[data,strings] = xlsread([datapath_bvars,'\Georgiadis_Jarocinski_2025_replication_dataset_bvars_with_shocks.xlsx']);
varnames = strings(1,2:end);
varnames(:,strmatch('time',varnames,'exact')) = [];
timevec  = strings(2:end,1);
tobedropped = []; % drop duplicates in the dataset
for j=1:length(varnames)
    temp = strmatch(varnames{j},varnames,'exact');
    if length(temp)>1
        tobedropped = [tobedropped; temp(2:end)];
    end
end
varnames(:,tobedropped) = [];
data(:,tobedropped) = [];



%% Specify BVAR settings
settings_bvar_baseline.covid                     = 1; % 1: Zero out shocks at beginning of COVID
settings_bvar_baseline.covidfull                 = 0; % 1: Zero out all shocks during COVID
settings_bvar_baseline.taptantr                  = 0; % 1: Zero out shocks ar taper tantrum
settings_bvar_baseline.prior.lags                = 12;
settings_bvar_baseline.prior.minnesota.tightness = .2;
settings_bvar_baseline.prior.minnesota.decay     = 1;
settings_bvar_baseline.ndraws                    = 2000;
settings_bvar_baseline.detspec                   = 'const'; % 'const' or 'ttrend'
settings_bvar_baseline.mindate                   = [{'1991m1'}];
settings_bvar_baseline.maxdate                   = [{'2024m6'}];
settings_bvar_baseline.endovarname               = [{'tb_rate_1y_eop'},{'tb_rate_10y_eop'},{'lsp500_us_eop'},{'ebp'},{'lmrgdp_us'},{'lgdpdefl_us'}];
settings_bvar_baseline.shockvarname              = [{'cmp'},{'ofg'},{'lsap'},{'dfg'}];
settings_bvar_baseline.prior.minnesota.mvector   = [0,0,0,1,0,1,1,1]; % 0 for stationary variables, 1 for nonstationary variables
settings_bvar_baseline.shocks_point_vs_dist      = 'dist'; % or 'point'
settings_bvar_baseline.W_dist.surprname          = [{'surpr_ed1'},{'surpr_tfut02'},{'surpr_tfut10'},{'surpr_sp500fut'}];
settings_bvar_baseline.W_dist.path               = datapath_bvars;
settings_bvar_baseline.W_dist.name               = 'shock_dist.mat';
settings_bvar_baseline.irfvarname                = [{'lmrgdp_us'},{'US real GDP (\%)'};...
                                                    {'lgdpdefl_us'},{'US GDP deflator (\%)'};...
                                                    {'lcpi_us'},{'US CPI (\%)'};...
                                                    {'ebp'},{'EBP (pp)'};...
                                                    {'tb_rate_1y_eop'},{'1Y TB rate (pp)'};...
                                                    {'tb_rate_10y_eop'},{'10Y TB rate (pp)'};...
                                                    {'lsp500_us_eop'},{'S\&P 500 (\%)'};...
                                                    {'lip_exconstr_us'},{'IP (\%)'};...
                                                    {'lmrgdp_exus'},{'RoW real GDP (\%)'};...
                                                    {'lip_exus_pw'},{'RoW IP (\%)'};...
                                                    {'lcpi_exus_pw'},{'RoW CPI (\%)'};...
                                                    {'lreer_cpi_us'},{'REER (\%)'};...
                                                    {'lrexports_us'},{'US exports (\%)'};...
                                                    {'lrimports_us'},{'US imports (\%)'};...
                                                    {'riskaversion_bex_eop'},{'Risk aversion (index)'};...
                                                    {'lmsci_exus_eop'},{'MSCI World ex US (\%)'};...
                                                    {'hyspread_us'},{'HY-spread US (pp)'};...
                                                    {'hyspread_eur'},{'HY-spread EUR (pp)'};...
                                                    {'hyspread_eme'},{'HY-spread EME (pp)'};...
                                                    {'tp10_gdpw'},{'AE TP (pp)'};...
                                                    {'tp10_us'},{'TP US (pp)'};...
                                                    {'tp10_de'},{'TP DEU (pp)'};...
                                                    {'tp10_ch'},{'TP CHE (pp)'};...
                                                    {'tp10_nz'},{'TP NZL (pp)'};...
                                                    {'tp10_au'},{'TP AUS (pp)'};...
                                                    {'tp10_uk'},{'TP UK (pp)'};...
                                                    {'tp10_jp'},{'TP JPN (pp)'};...
                                                    {'tp10_ca'},{'TP CAN (pp)'};...
                                                    {'tp10_se'},{'TP SWE (pp)'};...
                                                    {'lpcomm'},{'IMF energy (\%)'};...
                                                    {'lpcomm_crb'},{'CRB (\%)'};...
                                                    {'lneer_us'},{'US NEER (\%)'};...
                                                    {'lneer_ae_us'},{'US-AE NEER (\%)'};...
                                                    {'lneer_eme_us'},{'US-EME NEER (\%)'};...
                                                    {'lip_emeexus_pw'},{'EME IP (\%)'};...
                                                    {'lmrgdp_emeexus'},{'EME real GDP (\%)'};...
                                                    {'lcpi_emeexus_pw'},{'EME CPI (\%)'};...
                                                    {'lip_aeexus_pw'},{'AE IP (\%)'};...
                                                    {'lmrgdp_aeexus'},{'AE real GDP (\%)'};...
                                                    {'lcpi_aeexus_pw'},{'AE CPI (\%)'};...
                                                    {'glfac_riskyap'},{'GF asset prices (index)'};...
                                                    {'lwtrade_nonus'},{'World trade ex US (\%)'}];
settings_bvar_baseline.irfvarname_toplot         = settings_bvar_baseline.irfvarname;
settings_bvar_baseline.irfhor                    = 36;
settings_bvar_baseline.shockvarname_toplot       = settings_bvar_baseline.shockvarname;
settings_bvar_baseline.irfhor_toplot             = settings_bvar_baseline.irfhor;
settings_bvar_baseline.shocks_common_yaxis       = [1,2,3,4]; % which shocks to consider among those that are plotted (settings_baseline.shockvars_toplot) in determining common y-axis limits for the plots

%% BVAR estimation for IRFs shown in Figures 3-6, 9-10, and 15 (rows 1 and 2)
display('    ')
display('Estimating IRFs for Figures 3-6, 9-10, and 15 (rows 1 and 2)')
display('    ')
IRFs_bvar_baseline = produce_irfs_bvar(settings_bvar_baseline,varnames,data,timevec);

%% Plot BVAR IRFs for RoW and US together as shown in Figure 3 (rows 3 and 4), Figure 5 (rows 5 and 6), Figure 6 (RHS), Figure B.5-B.6
depvarname_rowus = [{'lip_exus_pw'},{'lip_exconstr_us'},{'IP (\%)'},{'lip'};...
                    {'lmrgdp_exus'},{'lmrgdp_us'},{'Real GDP (\%)'},{'lmrgdp'};...
                    {'lcpi_exus_pw'},{'lcpi_us'},{'CPI (\%)'},{'lcpi'};...
                    {'lip_aeexus_pw'},{'lip_exconstr_us'},{'IP (\%)'},{'lip_ae'};...
                    {'lmrgdp_aeexus'},{'lmrgdp_us'},{'Real GDP (\%)'},{'lmrgdp_ae'};...
                    {'lcpi_aeexus_pw'},{'lcpi_us'},{'CPI (\%)'},{'lcpi_ae'};...
                    {'lip_emeexus_pw'},{'lip_exconstr_us'},{'IP (\%)'},{'lip_eme'};...
                    {'lmrgdp_emeexus'},{'lmrgdp_us'},{'Real GDP (\%)'},{'lmrgdp_eme'};...
                    {'lcpi_emeexus_pw'},{'lcpi_us'},{'CPI (\%)'},{'lcpi_eme'};...
                    {'lmsci_exus_eop'},{'lsp500_us_eop'},{'Equity prices (\%)'},{'equityprices'};...
                    {'hyspread_eur'},{'hyspread_us'},{'Spreads (pp)'},{'hyspreadeur'};...
                    {'hyspread_eme'},{'hyspread_us'},{'Spreads (pp)'},{'hyspreademe'};...
                    {'tp10_gdpw'},{'tp10_us'},{'TP (pp)'},{'tp10'};...
                    {'tp10_de'},{'tp10_us'},{'DEU (pp)'},{'tp10_deu'};...
                    {'tp10_ch'},{'tp10_us'},{'CHE (pp)'},{'tp10_che'};...
                    {'tp10_nz'},{'tp10_us'},{'NZL (pp)'},{'tp10_nzl'};...
                    {'tp10_au'},{'tp10_us'},{'AUS (pp)'},{'tp10_aus'};...
                    {'tp10_uk'},{'tp10_us'},{'UK (pp)'},{'tp10_gbr'};...
                    {'tp10_jp'},{'tp10_us'},{'JPN (pp)'},{'tp10_jpn'};...
                    {'tp10_ca'},{'tp10_us'},{'CAN (pp)'},{'tp10_can'};...
                    {'tp10_se'},{'tp10_us'},{'SWE (pp)'},{'tp10_swe'}];
plot_bvar_irfs_rowus(settings_bvar_baseline,depvarname_rowus,IRFs_bvar_baseline,figurepath_bvars,'bl')

%% Plot comparison of BVAR IRF estimates to OLS and SLP IRF estimates produced using replicatoin package of Li et al as shown 
%    in Figure 3 (rows 1 and 2), Figure 4, Figure 5 (rows 1 to 4), Figure 6 (LHS), Figure 9-10, Figure 15 (rows 1 and 2), and Figure B.5   
depvarname_lietal = settings_bvar_baseline.irfvarname;
plot_bvar_irfs_with_lietal_estimators(settings_bvar_baseline,generalpath_bvars,figurepath_bvars,varnames,data,timevec,depvarname_lietal,IRFs_bvar_baseline,'bvar');

%% BVAR estimation for IRF with shorter horizons shown in Figures 7-8 and Figure 15 (row 3)
display('    ')
display('Estimating IRFs for Figures 7-8 and Figure 15 (row 3)')
display('    ')
settings_bvar_shorth = settings_bvar_baseline;
settings_bvar_shorth.irfhor       = 9;
settings_bvar_shorth.irfhor_toplot= settings_bvar_shorth.irfhor;
settings_bvar_shorth.irfvarname   = [{'outfl_bjupd_fromus_b_row_sby'},{'Bonds (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_e_row_sby'},{'Equity (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_b_ae_sby'},{'Bonds (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_e_ae_sby'},{'Equity (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_b_eme_sby'},{'Bonds (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_e_eme_sby'},{'Equity (\% of GDP)'};...
                                    {'ae_cgr_PFD_out_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'ae_cgr_PFE_out_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'ae_cgr_OTH_out_imf_y'},{'Other Inv. (\% of GDP)'};... 
                                    {'em_cgr_PFD_in_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'em_cgr_PFE_in_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'em_cgr_OTH_in_imf_y'},{'Other Inv. (\% of GDP)'};... 
                                    {'us_cgr_PFD_out_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'us_cgr_PFE_out_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'infl_bjupd_tous_sb_ae_sby'},{'Public bonds (\% of GDP)'};...
                                    {'infl_bjupd_tous_rb_ae_sby'},{'Private bonds (\% of GDP)'};...
                                    {'em_risky_inflows'},{'EME inflows (\% of GDP)'};...
                                    {'glfac_capflows'},{'GF capital flows (index)'}];
settings_bvar_shorth.irfvarname_toplot  = settings_bvar_shorth.irfvarname;
IRFs_bvar_shorth                        = produce_irfs_bvar(settings_bvar_shorth,varnames,data,timevec);
depvarname_lietal                       = settings_bvar_shorth.irfvarname;
plot_bvar_irfs_with_lietal_estimators(settings_bvar_shorth,generalpath_bvars,figurepath_bvars,varnames,data,timevec,depvarname_lietal,IRFs_bvar_shorth,'bvar');


%% Robustness checks Figure B.4: General 
display('    ')
display('Estimating IRFs for robustness checks (Figure B.4)')
display('    ')
irfvarname_robustness    = [{'lip_exus_pw'},{'RoW IP (\%)'};...
                                                    {'ebp'},{'EBP (pp)'};...
                                                    {'lneer_us'},{'US NEER (\%)'};...
                                                    {'lmsci_exus_eop'},{'MSCI World ex US (\%)'};...
                                                    {'hyspread_eur'},{'HY-spread EUR (pp)'};...
                                                    {'tp10_gdpw'},{'AE TP (pp)'};...
                                                    {'lwtrade_nonus'},{'World trade ex US (\%)'}];

% Shorter lags
settings_bvar_robustness.shortlag                       = settings_bvar_baseline;
settings_bvar_robustness.shortlag.P_own                 = 3;
settings_bvar_robustness.shortlag.P_controls            = 3;
settings_bvar_robustness.shortlag.irfvarname            = irfvarname_robustness; 
settings_bvar_robustness.shortlag.irfvarname_toplot     = settings_bvar_robustness.shortlag.irfvarname;
settings_bvar_robustness.shortlag.shockvarname_toplot   = settings_bvar_robustness.shortlag.shockvarname;
Rob_collection.IRFs.shortlag                            = produce_irfs_bvar(settings_bvar_robustness.shortlag,varnames,data,timevec);
Rob_collection.title.shortlag                           = 'p=3';

% With linear time trend
settings_bvar_robustness.ttrend                      = settings_bvar_baseline;
settings_bvar_robustness.ttrend.timetrend            = 1;
settings_bvar_robustness.ttrend.irfvarname           = irfvarname_robustness; 
settings_bvar_robustness.ttrend.irfvarname_toplot    = settings_bvar_robustness.ttrend.irfvarname;
settings_bvar_robustness.ttrend.shockvarname_toplot  = settings_bvar_robustness.ttrend.shockvarname;
Rob_collection.IRFs.ttrend                           = produce_irfs_bvar(settings_bvar_robustness.ttrend,varnames,data,timevec);
Rob_collection.title.ttrend                          = 'Time trend';

% Additional endogenous variables
settings_bvar_robustness.addcontr                           = settings_bvar_baseline;
settings_bvar_robustness.addcontr.endovarname               = [settings_bvar_baseline.endovarname,{'lpoil'},{'lneer_us'},{'riskaversion_bex_eop'}]; 
settings_bvar_robustness.addcontr.prior.minnesota.mvector   = [settings_bvar_baseline.prior.minnesota.mvector,[1,1,1]]; 
settings_bvar_robustness.addcontr.irfvarname                = irfvarname_robustness; 
settings_bvar_robustness.addcontr.irfvarname_toplot         = settings_bvar_robustness.addcontr.irfvarname;
settings_bvar_robustness.addcontr.shockvarname_toplot       = settings_bvar_robustness.addcontr.shockvarname;
Rob_collection.IRFs.addcontr                                = produce_irfs_bvar(settings_bvar_robustness.addcontr,varnames,data,timevec);
Rob_collection.title.addcontr                               = 'Additional endogenous variables';

% Baseline
settings_bvar_robustness.baseline                       = settings_bvar_baseline;
settings_bvar_robustness.baseline.irfvarname            = irfvarname_robustness; 
settings_bvar_robustness.baseline.irfvarname_toplot     = settings_bvar_robustness.baseline.irfvarname;
settings_bvar_robustness.baseline.shockvarname_toplot   = settings_bvar_robustness.baseline.shockvarname;
Rob_collection.IRFs.baseline                            = produce_irfs_bvar(settings_bvar_robustness.baseline,varnames,data,timevec);
Rob_collection.title.baseline                           = 'Baseline';

plot_bvar_irfs_altspec_compar(settings_bvar_robustness.baseline,Rob_collection,figurepath_bvars,'rob')
clear Rob_collection settings_bvar_robustness


%% Robustness checks Figure B.3: LSAP shocks since 2008
display('    ')
display('Estimating IRFs for robustness checks (Figure B.3)')
display('    ')
irfvarname_robustness    = [{'lmrgdp_us'},{'US real GDP (\%)'};...
                                                    {'lgdpdefl_us'},{'US GDP deflator (\%)'};...
                                                    {'lcpi_us'},{'US CPI (\%)'};...
                                                    {'ebp'},{'EBP (pp)'};...
                                                    {'lsp500_us_eop'},{'S\&P 500 (\%)'};...
                                                    {'lip_exconstr_us'},{'US IP (\%)'};...
                                                    {'tb_rate_1y_eop'},{'1Y TB rate (pp)'};...
                                                    {'tb_rate_10y_eop'},{'10Y TB rate (pp)'};...
                                                    {'lip_exus_pw'},{'RoW IP (\%)'};...
                                                    {'lmsci_exus_eop'},{'MSCI World ex US (\%)'};...
                                                    {'hyspread_us'},{'HY-spread US (pp)'};...
                                                    {'hyspread_eur'},{'HY-spread EUR (pp)'};...
                                                    {'tp10_gdpw'},{'AE TP (pp)'};...
                                                    {'tp10_us'},{'US TP (pp)'};...
                                                    {'lneer_us'},{'US NEER (\%)'};...
                                                    {'lwtrade_nonus'},{'World trade ex US (\%)'};...
                                                    {'outfl_bjupd_fromus_b_ae_sby'},{'AE bonds (\% of GDP)'};...
                                                    {'outfl_bjupd_fromus_e_ae_sby'},{'AE equity (\% of GDP)'};...
                                                    {'outfl_bjupd_fromus_b_eme_sby'},{'EME bonds (\% of GDP)'};...
                                                    {'outfl_bjupd_fromus_e_eme_sby'},{'EM equity (\% of GDP)'}];
% LSAP shocks 0 before 2008
temp                                                            = data(:,strmatch('lsap',varnames,'exact'));
temp(data(:,strmatch('postgfcdummy',varnames,'exact'))==0,:)    = 0;
data                                                            = [data, temp];
varnames                                                        = [varnames, {'lsap2008'}];
settings_bvar_robustness.lsap2008                               = settings_bvar_baseline;
settings_bvar_robustness.lsap2008.shockvarname                  = [{'lsap2008'}];
settings_bvar_robustness.lsap2008.irfvarname                    = irfvarname_robustness; 
settings_bvar_robustness.lsap2008.irfvarname_toplot             = settings_bvar_robustness.lsap2008.irfvarname;
settings_bvar_robustness.lsap2008.shockvarname_toplot           = settings_bvar_robustness.lsap2008.shockvarname;
settings_bvar_robustness.lsap2008.shocks_point_vs_dist          = 'point'; % do not use full dsitribution of shocks because we set manually all shocks ot zero before 2008
Rob_collection.IRFs.lsap2008                                    = produce_irfs_bvar(settings_bvar_robustness.lsap2008,varnames,data,timevec);
Rob_collection.title.lsap2008                                   = 'LSAP shocks only after 2007';

% Baseline
settings_bvar_robustness.baseline                       = settings_bvar_baseline;
settings_bvar_robustness.baseline.shockvarname          = [{'lsap'}];
settings_bvar_robustness.baseline.irfvarname            = irfvarname_robustness; 
settings_bvar_robustness.baseline.irfvarname_toplot     = settings_bvar_robustness.baseline.irfvarname;
settings_bvar_robustness.baseline.shockvarname_toplot   = settings_bvar_robustness.baseline.shockvarname;
settings_bvar_robustness.baseline.shocks_point_vs_dist  = 'point'; % do not use full dsitribution of shocks because we set manually all shocks ot zero before 2008
Rob_collection.IRFs.baseline                            = produce_irfs_bvar(settings_bvar_robustness.baseline,varnames,data,timevec);
Rob_collection.title.baseline                           = 'Baseline';

plot_bvar_irfs_altspec_compar(settings_bvar_robustness.baseline,Rob_collection,figurepath_bvars,'rob_lsap2008')
clear Rob_collection settings_bvar_robustness


%% Robustness checks Figure B.8: No taper tantrum 
display('    ')
display('Estimating IRFs for robustness checks (Figure B.8)')
display('    ')
irfvarname_robustness    = [{'outfl_bjupd_fromus_b_ae_sby'},{'Bonds (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_e_ae_sby'},{'Equity (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_b_eme_sby'},{'Bonds (\% of GDP)'};...
                                    {'outfl_bjupd_fromus_e_eme_sby'},{'Equity (\% of GDP)'};...
                                    {'ae_cgr_PFD_out_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'ae_cgr_PFE_out_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'ae_cgr_OTH_out_imf_y'},{'Other Inv. (\% of GDP)'};... 
                                    {'em_cgr_PFD_in_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'em_cgr_PFE_in_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'em_cgr_OTH_in_imf_y'},{'Other Inv. (\% of GDP)'};... 
                                    {'us_cgr_PFD_out_imf_y'},{'Debt (\% of GDP)'};... 
                                    {'us_cgr_PFE_out_imf_y'},{'Equity (\% of GDP)'};... 
                                    {'riskaversion_bex_eop'},{'Risk aversion (index)'}];

% Jarocinski shocks with taper tantrum surprises set to 0
settings_bvar_robustness.notaptant                      = settings_bvar_baseline;
settings_bvar_robustness.notaptant.taptantr             = 1; 
settings_bvar_robustness.notaptant.irfhor               = 9;
settings_bvar_robustness.notaptant.irfhor_toplot        = settings_bvar_robustness.notaptant.irfhor;
settings_bvar_robustness.notaptant.irfvarname           = irfvarname_robustness; 
settings_bvar_robustness.notaptant.irfvarname_toplot    = settings_bvar_robustness.notaptant.irfvarname;
settings_bvar_robustness.notaptant.shockvarname_toplot  = settings_bvar_robustness.notaptant.shockvarname;
Rob_collection.IRFs.notaptant                           = produce_irfs_bvar(settings_bvar_robustness.notaptant,varnames,data,timevec);
Rob_collection.title.notaptant                          = 'No taper tantrum';

% Baseline
settings_bvar_robustness.baseline                       = settings_bvar_baseline;
settings_bvar_robustness.baseline.irfhor                = 9;
settings_bvar_robustness.baseline.irfhor_toplot         = settings_bvar_robustness.baseline.irfhor;
settings_bvar_robustness.baseline.irfvarname            = irfvarname_robustness; 
settings_bvar_robustness.baseline.irfvarname_toplot     = settings_bvar_robustness.baseline.irfvarname;
settings_bvar_robustness.baseline.shockvarname_toplot   = settings_bvar_robustness.baseline.shockvarname;
Rob_collection.IRFs.baseline                            = produce_irfs_bvar(settings_bvar_robustness.baseline,varnames,data,timevec);
Rob_collection.title.baseline                           = 'Baseline';

plot_bvar_irfs_altspec_compar(settings_bvar_robustness.baseline,Rob_collection,figurepath_bvars,'rob_notaptantr')
clear Rob_collection settings_bvar_robustness
 
 

%% Select and transfer shown in paper to Figure folder
sourcefolder = figurepath_bvars;
destinationfolder  = [superpath,'\Figures paper'];
figure_transfer_bvar(sourcefolder,destinationfolder)
eval(['rmdir ''',figurepath_bvars,''' s '])
eval(['delete ''',datapath_bvars,'\Georgiadis_Jarocinski_2025_replication_dataset_bvars_with_shocks.xlsx'' '])
eval(['delete ''',datapath_bvars,'\shock_dist.mat'' '])


