
function figure_transfer_bvar(sourcefolder,destinationfolder)

% Figure 3: Effects of US monetary policy shocks on non-US RoW real activity
foldername = 'Figure 3';
figurelist = [{'irf_litetalirfs_legend_bvar.pdf'},...
    {'irf_complietal_lmrgdp_exus_cmp_bvar.pdf'},...
    {'irf_complietal_lmrgdp_exus_ofg_bvar.pdf'},...
    {'irf_complietal_lmrgdp_exus_lsap_bvar.pdf'},...
    {'irf_complietal_lmrgdp_exus_dfg_bvar.pdf'},...
    {'irf_complietal_lip_exus_pw_cmp_bvar.pdf'},...
    {'irf_complietal_lip_exus_pw_ofg_bvar.pdf'},...
    {'irf_complietal_lip_exus_pw_lsap_bvar.pdf'},...
    {'irf_complietal_lip_exus_pw_dfg_bvar.pdf'},...
    {'irf_row_us_legend_bl.pdf'},...
    {'irf_bvar_lmrgdp_cmp_rowus_bl.pdf'},...
    {'irf_bvar_lmrgdp_ofg_rowus_bl.pdf'},...
    {'irf_bvar_lmrgdp_lsap_rowus_bl.pdf'},...
    {'irf_bvar_lmrgdp_dfg_rowus_bl.pdf'},...
    {'irf_bvar_lip_cmp_rowus_bl.pdf'},...
    {'irf_bvar_lip_ofg_rowus_bl.pdf'},...
    {'irf_bvar_lip_lsap_rowus_bl.pdf'},...
    {'irf_bvar_lip_dfg_rowus_bl.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)


% Figure 4: Effects of US monetary policy shocks on non-US AE and EME real activity
foldername = 'Figure 4';
figurelist=[{'irf_complietal_lip_aeexus_pw_cmp_bvar.pdf'},...
    {'irf_complietal_lip_aeexus_pw_ofg_bvar.pdf'},...
    {'irf_complietal_lip_aeexus_pw_lsap_bvar.pdf'},...
    {'irf_complietal_lip_aeexus_pw_dfg_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_cmp_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_ofg_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_lsap_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 5: Effects of US monetary policy shocks non-US RoW financial variables
foldername = 'Figure 5';
figurelist=[{'irf_litetalirfs_legend_bvar.pdf'},...
    {'irf_complietal_riskaversion_bex_eop_cmp_bvar.pdf'},...
    {'irf_complietal_riskaversion_bex_eop_ofg_bvar.pdf'},...
    {'irf_complietal_riskaversion_bex_eop_lsap_bvar.pdf'},...
    {'irf_complietal_riskaversion_bex_eop_dfg_bvar.pdf'},...
    {'irf_complietal_hyspread_eur_cmp_bvar.pdf'},...
    {'irf_complietal_hyspread_eur_ofg_bvar.pdf'},...
    {'irf_complietal_hyspread_eur_lsap_bvar.pdf'},...
    {'irf_complietal_hyspread_eur_dfg_bvar.pdf'},...
    {'irf_complietal_hyspread_eme_cmp_bvar.pdf'},...
    {'irf_complietal_hyspread_eme_ofg_bvar.pdf'},...
    {'irf_complietal_hyspread_eme_lsap_bvar.pdf'},...
    {'irf_complietal_hyspread_eme_dfg_bvar.pdf'},...
    {'irf_complietal_lmsci_exus_eop_cmp_bvar.pdf'},...
    {'irf_complietal_lmsci_exus_eop_ofg_bvar.pdf'},...
    {'irf_complietal_lmsci_exus_eop_lsap_bvar.pdf'},...
    {'irf_complietal_lmsci_exus_eop_dfg_bvar.pdf'},...
    {'irf_row_us_legend_bl.pdf'},...
    {'irf_bvar_hyspreadeur_cmp_rowus_bl.pdf'},...
    {'irf_bvar_hyspreadeur_ofg_rowus_bl.pdf'},...
    {'irf_bvar_hyspreadeur_lsap_rowus_bl.pdf'},...
    {'irf_bvar_hyspreadeur_dfg_rowus_bl.pdf'},...
    {'irf_bvar_equityprices_cmp_rowus_bl.pdf'},...
    {'irf_bvar_equityprices_ofg_rowus_bl.pdf'},...
    {'irf_bvar_equityprices_lsap_rowus_bl.pdf'},...
    {'irf_bvar_equityprices_dfg_rowus_bl.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 6: Effects of LSAP shocks on AE sovereign-bond term premia
foldername = 'Figure 6';
figurelist=[{'irf_complietal_tp10_gdpw_lsap_vartitle_bvar.pdf'},...
    {'irf_bvar_tp10_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'},...
    {'irf_row_us_legend_bl.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 7: Effects of US monetary policy shockson US portfolio outflows by destination and instrument, scaled by lagged US GDP
foldername = 'Figure 7';
figurelist=[{'irf_complietal_outfl_bjupd_fromus_b_ae_sby_cmp_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_ae_sby_ofg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_ae_sby_lsap_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_ae_sby_dfg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_ae_sby_cmp_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_ae_sby_ofg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_ae_sby_lsap_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_ae_sby_dfg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_eme_sby_cmp_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_eme_sby_ofg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_eme_sby_lsap_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_b_eme_sby_dfg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_eme_sby_cmp_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_eme_sby_ofg_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_eme_sby_lsap_bvar.pdf'},...
    {'irf_complietal_outfl_bjupd_fromus_e_eme_sby_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 8: Effects of US monetary policy shocks on non-US AE portfolio outflows and EME portfolio inflows, scaled by lagged GDP
foldername = 'Figure 8';
figurelist=[{'irf_complietal_ae_cgr_PFD_out_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFD_out_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFD_out_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFD_out_imf_y_dfg_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFE_out_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFE_out_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFE_out_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_ae_cgr_PFE_out_imf_y_dfg_bvar.pdf'},...
    {'irf_complietal_ae_cgr_OTH_out_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_ae_cgr_OTH_out_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_ae_cgr_OTH_out_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_ae_cgr_OTH_out_imf_y_dfg_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFD_in_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFD_in_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFD_in_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFD_in_imf_y_dfg_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFE_in_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFE_in_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFE_in_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_em_cgr_PFE_in_imf_y_dfg_bvar.pdf'},...
    {'irf_complietal_em_cgr_OTH_in_imf_y_cmp_bvar.pdf'},...
    {'irf_complietal_em_cgr_OTH_in_imf_y_ofg_bvar.pdf'},...
    {'irf_complietal_em_cgr_OTH_in_imf_y_lsap_bvar.pdf'},...
    {'irf_complietal_em_cgr_OTH_in_imf_y_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 9: Effects of US monetary policy shocks on the dollar NEER
foldername = 'Figure 9';
figurelist=[{'irf_complietal_lneer_ae_us_cmp_bvar.pdf'},...
    {'irf_complietal_lneer_ae_us_ofg_bvar.pdf'},...
    {'irf_complietal_lneer_ae_us_lsap_bvar.pdf'},...
    {'irf_complietal_lneer_ae_us_dfg_bvar.pdf'},...
    {'irf_complietal_lneer_eme_us_cmp_bvar.pdf'},...
    {'irf_complietal_lneer_eme_us_ofg_bvar.pdf'},...
    {'irf_complietal_lneer_eme_us_lsap_bvar.pdf'},...
    {'irf_complietal_lneer_eme_us_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 10: Effects of US monetary policy shocks on the dollar real effective exchange rate and US real exports and imports
foldername = 'Figure 10';
figurelist=[{'irf_complietal_lreer_cpi_us_cmp_bvar.pdf'},...
    {'irf_complietal_lreer_cpi_us_ofg_bvar.pdf'},...
    {'irf_complietal_lreer_cpi_us_lsap_bvar.pdf'},...
    {'irf_complietal_lreer_cpi_us_dfg_bvar.pdf'},...
    {'irf_complietal_lrexports_us_cmp_bvar.pdf'},...
    {'irf_complietal_lrexports_us_ofg_bvar.pdf'},...
    {'irf_complietal_lrexports_us_lsap_bvar.pdf'},...
    {'irf_complietal_lrexports_us_dfg_bvar.pdf'},...
    {'irf_complietal_lrimports_us_cmp_bvar.pdf'},...
    {'irf_complietal_lrimports_us_ofg_bvar.pdf'},...
    {'irf_complietal_lrimports_us_lsap_bvar.pdf'},...
    {'irf_complietal_lrimports_us_dfg_bvar.pdf'},...
    {'irf_complietal_lwtrade_nonus_cmp_bvar.pdf'},...
    {'irf_complietal_lwtrade_nonus_ofg_bvar.pdf'},...
    {'irf_complietal_lwtrade_nonus_lsap_bvar.pdf'},...
    {'irf_complietal_lwtrade_nonus_dfg_bvar.pdf'},...
    {'irf_complietal_lpcomm_crb_cmp_bvar.pdf'},...
    {'irf_complietal_lpcomm_crb_ofg_bvar.pdf'},...
    {'irf_complietal_lpcomm_crb_lsap_bvar.pdf'},...
    {'irf_complietal_lpcomm_crb_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure 15: Effects of US monetary policy shocks on EME variables
foldername = 'Figure 15';
figurelist=[{'irf_complietal_lip_emeexus_pw_cmp_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_ofg_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_lsap_bvar.pdf'},...
    {'irf_complietal_lip_emeexus_pw_dfg_bvar.pdf'},...
    {'irf_complietal_lcpi_emeexus_pw_cmp_bvar.pdf'},...
    {'irf_complietal_lcpi_emeexus_pw_ofg_bvar.pdf'},...
    {'irf_complietal_lcpi_emeexus_pw_lsap_bvar.pdf'},...
    {'irf_complietal_lcpi_emeexus_pw_dfg_bvar.pdf'},...
    {'irf_complietal_em_risky_inflows_cmp_bvar.pdf'},...
    {'irf_complietal_em_risky_inflows_ofg_bvar.pdf'},...
    {'irf_complietal_em_risky_inflows_lsap_bvar.pdf'},...
    {'irf_complietal_em_risky_inflows_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure B.3: Robustness of LSAP effects
foldername = 'Figure B3';
figurelist=[{'irf_bvar_lip_exconstr_us_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_lgdpdefl_us_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_lsp500_us_eop_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_tb_rate_10y_eop_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_ebp_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_tp10_us_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_tp10_gdpw_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_lneer_us_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_lmsci_exus_eop_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_lip_exus_pw_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_hyspread_eur_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_ae_sby_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_ae_sby_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_eme_sby_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_eme_sby_lsap_rob_lsap2008.pdf'},...
    {'irf_bvar_legend_rob_lsap2008.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure B.4: Effects of US monetary policy shocks estimated for alternative BVAR specifications
foldername = 'Figure B4';
figurelist=[{'irf_bvar_lip_exus_pw_cmp_rob.pdf'},...
    {'irf_bvar_lip_exus_pw_ofg_rob.pdf'},...
    {'irf_bvar_lip_exus_pw_lsap_rob.pdf'},...
    {'irf_bvar_lip_exus_pw_dfg_rob.pdf'},...
    {'irf_bvar_ebp_cmp_rob.pdf'},...
    {'irf_bvar_ebp_ofg_rob.pdf'},...
    {'irf_bvar_ebp_lsap_rob.pdf'},...
    {'irf_bvar_ebp_dfg_rob.pdf'},...
    {'irf_bvar_lneer_us_cmp_rob.pdf'},...
    {'irf_bvar_lneer_us_ofg_rob.pdf'},...
    {'irf_bvar_lneer_us_lsap_rob.pdf'},...
    {'irf_bvar_lneer_us_dfg_rob.pdf'},...
    {'irf_bvar_lmsci_exus_eop_cmp_rob.pdf'},...
    {'irf_bvar_lmsci_exus_eop_ofg_rob.pdf'},...
    {'irf_bvar_lmsci_exus_eop_lsap_rob.pdf'},...
    {'irf_bvar_lmsci_exus_eop_dfg_rob.pdf'},...
    {'irf_bvar_hyspread_eur_cmp_rob.pdf'},...
    {'irf_bvar_hyspread_eur_ofg_rob.pdf'},...
    {'irf_bvar_hyspread_eur_lsap_rob.pdf'},...
    {'irf_bvar_hyspread_eur_dfg_rob.pdf'},...
    {'irf_bvar_tp10_gdpw_cmp_rob.pdf'},...
    {'irf_bvar_tp10_gdpw_ofg_rob.pdf'},...
    {'irf_bvar_tp10_gdpw_lsap_rob.pdf'},...
    {'irf_bvar_tp10_gdpw_dfg_rob.pdf'},...
    {'irf_bvar_lwtrade_nonus_cmp_rob.pdf'},...
    {'irf_bvar_lwtrade_nonus_ofg_rob.pdf'},...
    {'irf_bvar_lwtrade_nonus_lsap_rob.pdf'},...
    {'irf_bvar_lwtrade_nonus_dfg_rob.pdf'},...
    {'irf_bvar_legend_rob.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure B.5: Effects of US monetary policy on global factor in risky asset prices
foldername = 'Figure B5';
figurelist=[{'irf_complietal_glfac_riskyap_cmp_bvar.pdf'},...
    {'irf_complietal_glfac_riskyap_ofg_bvar.pdf'},...
    {'irf_complietal_glfac_riskyap_lsap_bvar.pdf'},...
    {'irf_complietal_glfac_riskyap_dfg_bvar.pdf'},...
    {'irf_litetalirfs_legend_bvar.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure B.6: Effects of LSAP shocks on US and AE term premia
foldername = 'Figure B6';
figurelist=[{'irf_bvar_tp10_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_deu_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_gbr_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_can_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_che_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_swe_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_jpn_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_aus_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_bvar_tp10_nzl_lsap_rowus_vartitle_bl.pdf'},...
    {'irf_row_us_legend_bl.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)

% Figure B.8: Effects of US monetary policy shocks on US capital flows estimated without taper tantrum events
foldername = 'Figure B8';
figurelist=[{'irf_bvar_outfl_bjupd_fromus_b_ae_sby_cmp_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_ae_sby_ofg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_ae_sby_lsap_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_ae_sby_dfg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_ae_sby_cmp_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_ae_sby_ofg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_ae_sby_lsap_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_ae_sby_dfg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_eme_sby_cmp_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_eme_sby_ofg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_eme_sby_lsap_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_b_eme_sby_dfg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_eme_sby_cmp_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_eme_sby_ofg_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_eme_sby_lsap_rob_notaptantr.pdf'},...
    {'irf_bvar_outfl_bjupd_fromus_e_eme_sby_dfg_rob_notaptantr.pdf'},...
    {'irf_bvar_riskaversion_bex_eop_cmp_rob_notaptantr.pdf'},...
    {'irf_bvar_riskaversion_bex_eop_ofg_rob_notaptantr.pdf'},...
    {'irf_bvar_riskaversion_bex_eop_lsap_rob_notaptantr.pdf'},...
    {'irf_bvar_riskaversion_bex_eop_dfg_rob_notaptantr.pdf'},...
    {'irf_bvar_legend_rob_notaptantr.pdf'}];
copy_figure(figurelist,sourcefolder,destinationfolder,foldername)








